etcd: ../../../../../../bin/etcd  --data-dir /tmp/etcd.data$PORT
doorman: $GOPATH/bin/doorman -logtostderr -config=./config.yml -port=15000 -debug_port=15050 -etcd_endpoints=http://localhost:2379 -master_election_lock=/doorman.master -hostname=localhost

